# Data Cleaning and Preparation

In [1]:
import numpy as np
import pandas as pd
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

## Handling Missing Data

In [2]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data
print(string_data.isnull())
print(string_data.notnull())

0    False
1    False
2     True
3    False
dtype: bool
0     True
1     True
2    False
3     True
dtype: bool


In [3]:
string_data[0] = None
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

### Filtering Out Missing Data

In [4]:
from numpy import nan as NA
data = pd.Series([1, NA, 3.5, NA, 7])
print(data)
print(data.fillna(9000000))
print(data.dropna())


0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64
0          1.0
1    9000000.0
2          3.5
3    9000000.0
4          7.0
dtype: float64
0    1.0
2    3.5
4    7.0
dtype: float64


In [5]:
print(data)
print(data.notnull())
print(data[data.notnull()])

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64
0     True
1    False
2     True
3    False
4     True
dtype: bool
0    1.0
2    3.5
4    7.0
dtype: float64


In [7]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
                     [NA, NA, NA], [NA, 6.5, 3.]])
print(data)
cleaned = data.dropna()
print(data)
print(cleaned)

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0
     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0
     0    1    2
0  1.0  6.5  3.0


In [9]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [10]:
data[4]=NA
print(data)

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN


In [11]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [12]:
df = pd.DataFrame(np.random.randn(7, 3))
print(df)
df.iloc[:4, 1] = NA
print(df)

df.iloc[:2, 2] = NA
print(df)
print(df.dropna())
print(df.dropna(thresh=2))

          0         1         2
0 -0.204708  0.478943 -0.519439
1 -0.555730  1.965781  1.393406
2  0.092908  0.281746  0.769023
3  1.246435  1.007189 -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741
          0         1         2
0 -0.204708       NaN -0.519439
1 -0.555730       NaN  1.393406
2  0.092908       NaN  0.769023
3  1.246435       NaN -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741
          0         1         2
0 -0.204708       NaN       NaN
1 -0.555730       NaN       NaN
2  0.092908       NaN  0.769023
3  1.246435       NaN -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741
          0         1         2
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741
          0         1         2
2  0.092908       NaN  0.769023
3  1.246435       NaN -1.296221
4  0.274

### Filling In Missing Data

In [13]:
df

0         1         2
0 -0.204708       NaN       NaN
1 -0.555730       NaN       NaN
2  0.092908       NaN  0.769023
3  1.246435       NaN -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [14]:
df.fillna(0)

0         1         2
0 -0.204708  0.000000  0.000000
1 -0.555730  0.000000  0.000000
2  0.092908  0.000000  0.769023
3  1.246435  0.000000 -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [15]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0 -0.204708  0.500000  0.000000
1 -0.555730  0.500000  0.000000
2  0.092908  0.500000  0.769023
3  1.246435  0.500000 -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [16]:
_ = df.fillna(0, inplace=True)
df

0         1         2
0 -0.204708  0.000000  0.000000
1 -0.555730  0.000000  0.000000
2  0.092908  0.000000  0.769023
3  1.246435  0.000000 -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [20]:
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[2:, 1] = NA
df.iloc[4:, 2] = NA
df
print(df.fillna(method='ffill'))
df.fillna(method='ffill', limit=2)

          0         1         2
0  0.022185  0.758363 -0.660524
1  0.862580 -0.010032  0.050009
2  0.670216 -0.010032 -0.955869
3 -0.023493 -0.010032 -0.652469
4 -1.218302 -0.010032 -0.652469
5  0.723642 -0.010032 -0.652469


0         1         2
0  0.022185  0.758363 -0.660524
1  0.862580 -0.010032  0.050009
2  0.670216 -0.010032 -0.955869
3 -0.023493 -0.010032 -0.652469
4 -1.218302       NaN -0.652469
5  0.723642       NaN -0.652469

In [18]:
print(df.fillna(method='ffill'))

          0         1         2
0  0.476985  3.248944 -1.021228
1 -0.577087  0.124121  0.302614
2  0.523772  0.124121  1.343810
3 -0.713544  0.124121 -2.370232
4 -1.860761  0.124121 -2.370232
5 -1.265934  0.124121 -2.370232


In [21]:
data = pd.Series([1., NA, 3.5, NA, 7])
print(data.mean())
data.fillna(data.mean())

3.8333333333333335


0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

## Data Transformation

### Removing Duplicates

In [22]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [23]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [24]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [25]:
data['v1'] = range(7)
print(data)
data.drop_duplicates(['k1'])

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6


k1  k2  v1
0  one   1   0
1  two   1   1

In [26]:
print(data)
print(data.drop_duplicates(['k1'], keep='last'))
print(data.drop_duplicates(['k1','k2'], keep='last'))
print(data.drop_duplicates(['k1','k2','v1'], keep='last'))
print(data.drop_duplicates(['k1','v1'], keep='last'))

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6
    k1  k2  v1
4  one   3   4
6  two   4   6
    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6
    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6
    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6


### Transforming Data Using a Function or Mapping

In [27]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
                              'Pastrami', 'corned beef', 'Bacon',
                              'pastrami', 'honey ham', 'nova lox'],
                     'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [28]:
meat_to_animal = {
  'bacon': 'pig',
  'pulled pork': 'pig',
  'pastrami': 'cow',
  'corned beef': 'cow',
  'honey ham': 'pig',
  'nova lox': 'salmon'
}
meat_to_animal

{'bacon': 'pig',
 'corned beef': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon',
 'pastrami': 'cow',
 'pulled pork': 'pig'}

In [29]:
lowercased = data['food'].str.lower()
print(lowercased)

print(lowercased.map(meat_to_animal))
data['animal'] = lowercased.map(meat_to_animal)

print(data)

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object
0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object
          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon


In [30]:
data['food'] = data['food'].map(lambda x: meat_to_animal[x.lower()])
print(data)

     food  ounces  animal
0     pig     4.0     pig
1     pig     3.0     pig
2     pig    12.0     pig
3     cow     6.0     cow
4     cow     7.5     cow
5     pig     8.0     pig
6     cow     3.0     cow
7     pig     5.0     pig
8  salmon     6.0  salmon


### Replacing Values

In [33]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [32]:
data.replace(-999, np.nan)

food  ounces  animal
0     pig     4.0     pig
1     pig     3.0     pig
2     pig    12.0     pig
3     cow     6.0     cow
4     cow     7.5     cow
5     pig     8.0     pig
6     cow     3.0     cow
7     pig     5.0     pig
8  salmon     6.0  salmon

In [31]:
data.replace([-999, -1000], np.nan)

food  ounces  animal
0     pig     4.0     pig
1     pig     3.0     pig
2     pig    12.0     pig
3     cow     6.0     cow
4     cow     7.5     cow
5     pig     8.0     pig
6     cow     3.0     cow
7     pig     5.0     pig
8  salmon     6.0  salmon

In [34]:
data.replace([-999, -1000], [100, 200])

0      1.0
1    100.0
2      2.0
3    100.0
4    200.0
5      3.0
dtype: float64

In [35]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### Renaming Axis Indexes

In [38]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [39]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [40]:
transform = lambda x: x[:4].upper()
data.index.map(transform)
data


one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [41]:
transform = lambda x: x[:].upper()
data.columns.map(transform)
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [42]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

In [43]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [44]:
data.rename(index={'OHIO': 'INDIANA'},
            columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA     0    1         2     3
COLORADO    4    5         6     7
NEW YORK    8    9        10    11

In [45]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)
data

one  two  three  four
INDIANA     0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

### Discretization and Binning

In [46]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [47]:
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
print(type(cats))
print(cats)

<class 'pandas.core.arrays.categorical.Categorical'>
[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]


In [48]:
print(cats.codes)
print(cats.categories)
print(pd.value_counts(cats))

[0 0 0 1 0 0 2 1 3 2 2 1]
IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')
(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64


In [49]:
cat = pd.cut(ages, [18, 26, 36, 61, 100], right=False)
print(cat.codes)

[0 0 0 1 0 0 2 1 3 2 2 1]


In [50]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [51]:
data = np.random.rand(20)
pd.cut(data, 4, precision=2)

[(0.72, 0.96], (0.02, 0.26], (0.02, 0.26], (0.26, 0.49], (0.49, 0.72], ..., (0.26, 0.49], (0.02, 0.26], (0.72, 0.96], (0.49, 0.72], (0.49, 0.72]]
Length: 20
Categories (4, interval[float64]): [(0.02, 0.26] < (0.26, 0.49] < (0.49, 0.72] < (0.72, 0.96]]

In [52]:
data = np.random.randn(1000)  # Normally distributed
cats = pd.qcut(data, 4)  # Cut into quartiles
cats
pd.value_counts(cats)

(0.604, 3.928]                   250
(-0.0453, 0.604]                 250
(-0.686, -0.0453]                250
(-2.9499999999999997, -0.686]    250
dtype: int64

In [53]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(-1.191, -0.0453], (-1.191, -0.0453], (1.287, 3.928], (-0.0453, 1.287], (-0.0453, 1.287], ..., (-1.191, -0.0453], (-0.0453, 1.287], (-2.9499999999999997, -1.191], (-0.0453, 1.287], (-0.0453, 1.287]]
Length: 1000
Categories (4, interval[float64]): [(-2.9499999999999997, -1.191] < (-1.191, -0.0453] < (-0.0453, 1.287] <
                                    (1.287, 3.928]]

### Detecting and Filtering Outliers

In [ ]:
data = pd.DataFrame(np.random.randn(1000, 4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.049091     0.026112    -0.002544    -0.051827
std       0.996947     1.007458     0.995232     0.998311
min      -3.645860    -3.184377    -3.745356    -3.428254
25%      -0.599807    -0.612162    -0.687373    -0.747478
50%       0.047101    -0.013609    -0.022158    -0.088274
75%       0.756646     0.695298     0.699046     0.623331
max       2.653656     3.525865     2.735527     3.366626

In [ ]:
col = data[2]
col[np.abs(col) > 3]

41    -3.399312
136   -3.745356
Name: 2, dtype: float64

In [ ]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
41   0.457246 -0.025907 -3.399312 -0.974657
60   1.951312  3.260383  0.963301  1.201206
136  0.508391 -0.196713 -3.745356 -1.520113
235 -0.242459 -3.056990  1.918403 -0.578828
258  0.682841  0.326045  0.425384 -3.428254
322  1.179227 -3.184377  1.369891 -1.074833
544 -3.548824  1.553205 -2.186301  1.277104
635 -0.578093  0.193299  1.397822  3.366626
782 -0.207434  3.525865  0.283070  0.544635
803 -3.645860  0.255475 -0.549574 -1.907459

In [ ]:
data[np.abs(data) > 3] = np.sign(data) * 3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.050286     0.025567    -0.001399    -0.051765
std       0.992920     1.004214     0.991414     0.995761
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.599807    -0.612162    -0.687373    -0.747478
50%       0.047101    -0.013609    -0.022158    -0.088274
75%       0.756646     0.695298     0.699046     0.623331
max       2.653656     3.000000     2.735527     3.000000

In [ ]:
np.sign(data).head()

0    1    2    3
0 -1.0  1.0 -1.0  1.0
1  1.0 -1.0  1.0 -1.0
2  1.0  1.0  1.0 -1.0
3 -1.0 -1.0  1.0 -1.0
4 -1.0  1.0 -1.0 -1.0

### Permutation and Random Sampling

In [ ]:
arr = np.arange(9).reshape((3, 3))
print(arr)
per=np.random.permutation(arr)
print(per)



[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [6 7 8]
 [0 1 2]]


In [ ]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))
sampler = np.random.permutation(5)
print(df)
print(sampler)

    0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19
[2 1 0 4 3]


In [ ]:
df
df.take(sampler)

0   1   2   3
2   8   9  10  11
1   4   5   6   7
0   0   1   2   3
4  16  17  18  19
3  12  13  14  15

In [ ]:
df.sample(n=3)

0   1   2   3
3  12  13  14  15
4  16  17  18  19
2   8   9  10  11

In [ ]:
choices = pd.Series([5, 7, -1, 6, 4])
draws = choices.sample(n=3)
draws

2   -1
3    6
0    5
dtype: int64

### Computing Indicator/Dummy Variables

In [ ]:
import pandas as pd
df = pd.DataFrame({'key': ['5', '2', '1', '3', '1', '2'],
                   'data1': range(6)})
print(df)
pd.get_dummies(df['key'])

  key  data1
0   5      0
1   2      1
2   1      2
3   3      3
4   1      4
5   2      5


1  2  3  5
0  0  0  0  1
1  0  1  0  0
2  1  0  0  0
3  0  0  1  0
4  1  0  0  0
5  0  1  0  0

In [ ]:
dummies = pd.get_dummies(df['key'], prefix='Grade')
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

data1  Grade_1  Grade_2  Grade_3  Grade_5
0      0        0        0        0        1
1      1        0        1        0        0
2      2        1        0        0        0
3      3        0        0        1        0
4      4        1        0        0        0
5      5        0        1        0        0

In [ ]:
mnames = ['movie_id', 'title', 'genres']
movies = pd.read_table('/content/drive/MyDrive/pydata-book-2nd-edition.zip (Unzipped Files)/pydata-book-2nd-edition/datasets/movielens/movies.dat', sep='::',header=None, names=mnames)
movies[:10]

/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py:767: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return read_csv(**locals())


movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
all_genres = []
for x in movies.genres:
    all_genres.extend(x.split('|'))
genres = pd.unique(all_genres)

In [ ]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [ ]:
zero_matrix = np.zeros((len(movies), len(genres)))
dummies = pd.DataFrame(zero_matrix, columns=genres)

In [ ]:
gen = movies.genres[0]
gen.split('|')
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2])

In [ ]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1

In [ ]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))
movies_windic.iloc[0]

movie_id                                      1
title                          Toy Story (1995)
genres              Animation|Children's|Comedy
Genre_Animation                               1
Genre_Children's                              1
                               ...             
Genre_War                                     0
Genre_Musical                                 0
Genre_Mystery                                 0
Genre_Film-Noir                               0
Genre_Western                                 0
Name: 0, Length: 21, dtype: object

In [ ]:
np.random.seed(12345)
values = np.random.rand(10)
values
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

## String Manipulation

### String Object Methods

In [ ]:
val = 'hi, Hello Everyone, Good Evening'
len(val.split(',')[2])

13

In [ ]:
pieces = [x.strip() for x in val.split(',')]
len(pieces[2])

12

In [ ]:
len(pieces)

3

In [ ]:
first, second, third = pieces
print(first)
first + '::' + second + '::' + third

hi


'hi::Hello Everyone::Good Evening'

In [ ]:
'::'.join(pieces)

'_'.join(pieces)

'hi_Hello Everyone_Good Evening'

In [ ]:
print(val)
print('Goo' in val)
print(val.index(','))
print(val.find(':'))

hi, Hello Everyone, Good Evening
True
2
-1


In [ ]:
print(val)
print(val.index(','))

hi, Hello Everyone, Good Evening
2


In [ ]:
val.count(',')

2

In [ ]:
val.replace(',', '::')
#val.replace(',', '')

'hi:: Hello Everyone:: Good Evening'

In [ ]:
s1 = ['Sree Vidyanikethan Engineering College', 'Sree Vinayaka Mission', 'Sri padmavathy']


### Regular Expressions

In [ ]:
import re
text = "foo_bar\t baz_ \tqux"
re.split('\s+', text)

['foo_bar', 'baz_', 'qux']

In [ ]:
regex = re.compile('\s+')
regex.split(text)

['foo_bar', 'baz_', 'qux']

In [ ]:
regex.findall(text)

['\t ', ' \t']

In [ ]:
text = """dave_xyz@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

# re.IGNORECASE makes the regex case-insensitive
regex = re.compile(pattern, flags=re.IGNORECASE)

In [ ]:
regex.findall(text,0,35)

['dave_xyz@google.com']

In [ ]:
m = regex.search(text)
m
#text[m.start():m.end()]

<re.Match object; span=(0, 19), match='dave_xyz@google.com'>

In [ ]:
text = """davexyz@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""
pattern = r'[A-Z0-9.%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

print(regex.match(text))

<re.Match object; span=(0, 18), match='davexyz@google.com'>


In [ ]:
print(regex.sub('EMAIL', text))

EMAIL
Steve EMAIL
Rob EMAIL
Ryan EMAIL



In [ ]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'
regex = re.compile(pattern, flags=re.IGNORECASE)

In [ ]:
m = regex.match('wesm@bright.net')
print(m)
m.groups()

<re.Match object; span=(0, 15), match='wesm@bright.net'>


('wesm', 'bright', 'net')

In [ ]:
regex.findall(text)

[('davexyz', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [ ]:
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3', text))

Username: davexyz, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com



### Vectorized String Functions in pandas

In [ ]:
import numpy as np
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com',
        'Rob': 'rob@gmail.com', 'Wes': np.nan}
data = pd.Series(data)
print(data)
print(data.isnull())

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object
Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool


In [ ]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [ ]:
print(pattern)
print(type(data))
data.str.findall(pattern, flags=re.IGNORECASE)

([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})
<class 'pandas.core.series.Series'>


Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [ ]:
matches = data.str.match(pattern, flags=re.IGNORECASE)
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [ ]:
type(matches)

pandas.core.series.Series

In [ ]:
print(data)
data.str[0]

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object


Dave       d
Steve      s
Rob        r
Wes      NaN
dtype: object

In [ ]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [ ]:
pd.options.display.max_rows = PREVIOUS_MAX_ROWS

## Conclusion